package:
  name: matsim-vis
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.0.1") }}

source:
  path: .

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  script:
    - $PYTHON setup.py install

requirements:
  build:
    - python>=3.9
    - setuptools
  run:
    - python>=3.9
    - xopen
    - ffmpeg
    - matplotlib
